# Generated by Django 3.2 on 2021-04-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210413_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dscription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
